name: CI

on: [push]

jobs:
  compile:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ 3.10, 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Compile the code
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        run: |
          pip install -r requirements.txt
          python -m compileall -q .
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.10, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      run: |
        pip install -r requirements.txt
        pytest tests/ -v
