fail_fast: True
stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
        - id: trailing-whitespace
          stages: [commit, manual]
        - id: end-of-file-fixer
          stages: [commit, manual]
        - id: check-yaml
          stages: [commit, manual]
        - id: check-added-large-files
          stages: [commit, manual]
        - id: check-docstring-first
          stages: [commit, manual]
-   repo: local
    hooks:
      - id: compile
        name: Compile the code
        entry: python -m compileall -q .
        language: system
        stages: [ commit ]

-   repo: local
    hooks:
      - id: runtests
        name: Run unit tests
        entry: pytest tests
        pass_filenames: false
        language: system
        stages: [commit]
#-   repo: local
#    hooks:
#        - id: flakeFunctions
#          name: Check for the size of functions
#          entry: flake8 --ignore F,E,W,CFQ002 --max-function-length=50
#          types: [python]
#          language: script
#          stages: [commit]
# mypy being the slowest has to be in the end
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.790
#    hooks:
#    -   id: mypy
#        args: [--config-file, mypy.ini]
#        stages: [commit, manual]
