[tool.poetry]
name = "python-search"
version = "0.02"
description = ""
authors = ["JeanCarloMachado <jean.machado@getyourguide.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fire = "^0.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
